version: '3'

services:
  app:
    image: docker.io/library/example-spring:1.0-SNAPSHOT
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - PG_HOST=database
      - PG_PORT=5432
  database:
    image: postgres:14
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=expassword
      - POSTGRES_USER=exuser
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U exuser" ]
      interval: 2s
      timeout: 2s
      retries: 5