spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:15432}/exuser
    username: exuser
    password: expassword
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml